acme_test:
    resource: "@AcmeTestBundle/Resources/config/routing.yml"
    prefix:   /

azgil_gallery:
    resource: "@AzgilGalleryBundle/Resources/config/routing.yml"
    prefix:   /gallery

azgil_category:
    resource: "@AzgilCategoryBundle/Resources/config/routing.yml"
    prefix:   /

