parameters:
#    azgil_category.example.class: Azgil\CategoryBundle\Example

services:
#    azgil_category.example:
#        class: %azgil_category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
